hecrj/coffee

- src/lib.rs
Fixes #11 
Tried to stick to the style of the original code and documentation. Let me know if there are any issues.
> Add `Game::on_close_request`

- examples/input.rs
- src/graphics/window/event.rs
- src/input.rs
- src/lib.rs
#12 
This exposes the following additional `input::Event` variants: 
- `TextInput`: Triggers on text entry. Contains the character typed as a `char`.
- `CursorEntered`/`CursorLeft`: Triggers when the mouse cursor enters or leaves the game window, respectively.
- `MouseWheel`: Triggers when the mouse wheel is scrolled. Contains the number of horizontal and vertical lines scrolled as `f32`.
- `WindowFocused`/`WindowUnfocused`: Triggers when the game window gains or loses focus, respectively. (This was originally 1 event with a bool in winit; I split it into two to mirror `CursorEntered`/`CursorLeft`.)
- `WindowMoved`: Triggers when the game window is moved. Contains the new X and Y coordinates of the window as `f32`.
The naming will probably need updating to match your personal style. …
> Add numerous events and input display example

- Cargo.toml
- src/graphics/backend_gfx/mod.rs
- src/graphics/backend_wgpu/font.rs
- src/graphics/backend_wgpu/mod.rs
- src/graphics/window/frame.rs
Fixes #5.
This was pretty straightforward to integrate. I have:
* Added [`wgpu_glyph`] as a dependency.
* Implemented `gpu::Font` for the `wgpu_backend`. The implementation is very similar to the `gfx` backend.
The hard part was [`wgpu_glyph`], which still needs some improvements.
Currently, there are differences between `gfx` and `wgpu` font rendering. I suspect it is related to the way we deal (or do not deal) with gamma correction. I will open a new issue to further investigate this.
[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph
> Implement font rendering for `wgpu` backend

- Cargo.toml
- examples/colors.rs
- src/graphics/backend_gfx/font.rs
- src/graphics/backend_gfx/mod.rs
- src/graphics/backend_wgpu/font.rs
- src/graphics/backend_wgpu/mod.rs
- src/graphics/backend_wgpu/pipeline.rs
- src/graphics/backend_wgpu/surface.rs
- src/graphics/backend_wgpu/texture.rs
- src/graphics/color.rs
Yesterday, when I was implementing #18, I noticed text was rendering differently using `gfx` vs `wgpu`.
Here is how it looked when using OpenGL:
Here is how it looked when using Vulkan:
It's a subtle difference, but the OpenGL version is way more readable (look at the uppercase `I` glyph). The difference? Gamma correction.
This made me start researching about color spaces and how to deal with them, which almost drove me to insanity... But I _think_ I figured out the problem, and the solution is quite simple.
Monitors display colors in the sRGB color space. Therefore, if you have a framebuffer with a `(0.5, 0.5, 0.5)` color value, it will always display the same grey, independently of the format of the framebuffer.
`wgpu_glyph` stores a cache of glyphs in a texture of alpha values. This …
> Handle gamma correction properly

- src/debug/basic.rs
- src/debug/null.rs
- src/lib.rs
I think this will be important once we implement #17.
Here is how it looks now:
> Show time spent in `Debug::draw` in debug view

- Cargo.toml
- examples/color.rs
- examples/input.rs
- examples/particles.rs
- src/debug/basic.rs
- src/graphics/backend_gfx/font.rs
- src/graphics/backend_gfx/mod.rs
- src/graphics/backend_gfx/surface.rs
- src/graphics/backend_gfx/types.rs
- src/graphics/backend_wgpu/font.rs
- src/graphics/backend_wgpu/mod.rs
- src/graphics/backend_wgpu/surface.rs
- src/graphics/backend_wgpu/types.rs
- src/graphics/font.rs
- src/graphics/target.rs
- src/graphics/text.rs
- src/graphics/window/frame.rs
- src/load/loading_screen.rs
Fixes #24.
* Trait `Default` for `Text` was implemented.
* `Font::draw` now supports a `Target` instead of a `Frame`.
> Make `Font::draw` support a `Target` instead of a `Frame`

- examples/color.rs
- examples/input.rs
- examples/particles.rs
- src/graphics/mod.rs
- src/graphics/transformation.rs
- src/graphics/window/frame.rs
- src/graphics/window/mod.rs
- src/graphics/window/settings.rs
- src/lib.rs
- src/load/loading_screen.rs
Implements and closes #23.
Adds a `Window::toggle_fullscreen` method as well as adding a `fullscreen` attribute to `Settings` in case a user wants their game to start in fullscreen mode.
Additionally, the ability to toggle between fullscreen mode and windowed mode via the 'F' key is added to the 'particles' example.
> Fullscreen support

- src/graphics/canvas.rs
Implements and resolves #21.
Uses `width` and `height` methods of [`Canvas`](https://github.com/hecrj/coffee/blob/56ff3b4e992013b2438cf3b9c46fd5cf606e9d13/src/graphics/canvas.rs#L12) in order to convert absolute to relative coordinates, as in [`Image::draw`](https://github.com/hecrj/coffee/blob/56ff3b4e992013b2438cf3b9c46fd5cf606e9d13/src/graphics/image.rs#L103).
> `Canvas::draw` is now generic

- .travis.yml
- spirvtest
Implements and closes #22 
Adds a bash script that is executed on CI to see if the compiled SPIR-V differs from the source shader.
I wanted to test this "locally" before opening a PR but was unable to get Travis to test on my fork, so this is more of a work in progress than I would like.
> [WIP] Test SPIR-V differences on CI

- CHANGELOG.md
- Cargo.toml
- examples/particles.rs
- src/graphics/batch.rs
This PR implements the `Extend` and `ParallelExtend` traits for `Batch`.
The particles example has been updated to showcase its usage. It generates sprites and populates the `Batch` using multiple threads now!
> Implement `Extend` and `ParallelExtend` for `Batch`

- src/graphics/backend_gfx/font.rs
- src/graphics/backend_wgpu/font.rs
- src/graphics/font.rs
- src/ui/renderer/text.rs
Fixes #43.
The fix consists in using the brand new `GlyphBrush::glyph_bounds` method instead of `GlyphBrush::pixel_bounds` (see https://github.com/alexheretic/glyph-brush/issues/68). The `Text` widget measure function can directly return the result now!
> Fix `Font::measure` and `Text` widget

- src/graphics/mesh.rs
- src/ui/core/element.rs
- src/ui/core/renderer.rs
- src/ui/renderer.rs
This PR implements `Element::explain`, which marks the `Element` as _to be explained by the renderer_. It is inspired by [`elm-ui`'s `explain` attribute](https://package.elm-lang.org/packages/mdgriffith/elm-ui/latest/Element#explain).
It can be very useful for debugging your UI layout. For example:
> Implement `Element::explain`

- CHANGELOG.md
- examples/particles.rs
- src/graphics/batch.rs
- src/graphics/texture_array/batch.rs
- src/ui/renderer.rs
`Batch::draw` and `texture_array::Batch::draw` do not take a `position` argument anymore. Using `Target::transform` before drawing is preferred.
> Remove `position` argument from `Batch::draw`

- CHANGELOG.md
- examples/color.rs
- examples/input.rs
- src/graphics/font.rs
- src/ui/renderer.rs
`Font::load` has been renamed to `Font::load_from_bytes` for consistency.
> Rename `Font::load` to `Font::load_from_bytes`

- src/graphics/backend_gfx/surface.rs
- src/graphics/backend_wgpu/surface.rs
- src/graphics/window.rs
The surface resize method must be called when resizing in order for resizing to work properly on particular platforms such as wayland.
> Fix wayland surface resizing

- CHANGELOG.md
- examples/counter.rs
- examples/gamepad.rs
- examples/mesh.rs
- examples/particles.rs
- examples/ui.rs
- src/graphics.rs
- src/lib.rs
- src/load/task.rs
- src/ui.rs
Fixes #61.
- `Task::succeed` replaces the old `Task::new`.
- `Task::new` now supports a lazy operation that can fail.
> Improve `Task` consistency

- examples/mesh.rs
- examples/particles.rs
- src/input/keyboard_and_mouse.rs
- src/input/mouse.rs
- src/input/mouse/wheel_movement.rs
Implementation for #64 
Now KeyboardAndMouse can 
- Handle other mouse buttons than Left
- Track mouse wheel movements
- Detect cursor leaving game window
I decided against keeping the old interface so this is a breaking change.
Is it correct / convenient to track the mouse wheel movements as a point?
> Track more inputs in KeyboardAndMouse

- examples/mesh.rs
- examples/particles.rs
- src/input/keyboard.rs
- src/input/keyboard_and_mouse.rs
- src/input/mouse.rs
Fixes #68
Keyboard and Mouse are now separate Input's
> Split KeyboardAndMouse

- CHANGELOG.md
- src/graphics/color.rs
Fixes https://github.com/hecrj/coffee/issues/74.
> Color improvements

- Cargo.toml
- src/graphics/backend_wgpu/font.rs
- src/graphics/backend_wgpu/mod.rs
- src/graphics/backend_wgpu/quad.rs
- src/graphics/backend_wgpu/surface.rs
- src/graphics/backend_wgpu/texture.rs
- src/graphics/backend_wgpu/triangle.rs
Updates the `wgpu` backend to use the latest API. This should help us migrate to the new incoming release.
> Update `wgpu` backend to latest API

- .gitignore
- examples/progress.rs
- src/ui.rs
- src/ui/renderer.rs
- src/ui/renderer/progress_bar.rs
- src/ui/widget.rs
- src/ui/widget/progress_bar.rs
closes #45
Added `ProgressBar` widget and `progress` example. 
I decided to reuse button sprites for now, but this can be easily changed in future if needed.
> Implement a `ProgressBar` widget

- .gitignore
- Cargo.toml
- examples/counter.rs
- examples/gamepad.rs
- examples/input.rs
- examples/mesh.rs
- examples/particles.rs
- examples/ui.rs
- src/graphics/backend_gfx/mod.rs
- src/graphics/backend_gfx/texture.rs
- src/graphics/backend_wgpu/mod.rs
- src/graphics/backend_wgpu/texture.rs
- src/graphics/canvas.rs
- src/load/loading_screen.rs
- src/load/task.rs
- src/ui.rs
- src/ui/renderer.rs
- src/ui/renderer/panel.rs
- src/ui/widget.rs
- src/ui/widget/panel.rs
- tests/_graphics/mod.rs
- tests/_graphics/test.rs
- tests/_graphics/test/mesh.rs
- tests/graphics.rs
Fixes #16 and closes #89.
This PR implements an interactive integration test runner for the `graphics` module.
The test runner basically renders a suite of tests off-screen and compares the output with previously generated model images. If differences are detected, the test fails.
Once a new test is added, the runner asks to create a model image:
If differences are detected, the runner allows us to toggle an overlay to check the differences before failing:
If no differences are detected, the runner closes automatically and the test succeeds.
The test is ignored by default and does not run on CI _yet_. In order to run the test we need to provide the `--ignored` flag to `cargo test`:
```
cargo test --features vulkan -- --ignored
```
As of now, there is only a simple `Mesh` test implemented, …
> Integration tests for `graphics`

- src/graphics/backend_gfx/mod.rs
- src/graphics/backend_gfx/triangle.rs
- src/graphics/backend_wgpu/mod.rs
- src/graphics/backend_wgpu/triangle.rs
- src/graphics/mesh.rs
- src/graphics/target.rs
Fixes #87.
It also fixes a crash when rendering big meshes in OpenGL.
> Promote `Mesh` indices from `u16` to `u32`

- CHANGELOG.md
- src/timer.rs
Fixes #96.
The game will still tick in this case after approximately __`584942417355.072` years__ in most platforms. I think this is acceptable.
> Fix hang when `Game::TICKS_PER_SECOND` is `0`

- CHANGELOG.md
- examples/mesh.rs
- src/graphics/mesh.rs
Fixes #98.
- `Mesh::new_with_tolerance`, which allows to control the tolerance of line segment approximations.
- The `mesh` example now has a slider to control the tolerance.
> Mesh with custom tolerance

- src/graphics/image.rs
- src/ui/renderer.rs
- tests/_graphics/test.rs
This makes it possible to reuse the `DynamicImage` buffer, avoiding unnecessary allocations.
> Make `graphics::Image::from_image` borrow the image buffer

- Cargo.toml
- README.md
- src/graphics/backend_wgpu/surface.rs
Fixes #124 and closes #125. Also bumps version.
> Fix swapchain usage in wgpu backend
